### ISSUE TITLE
Leaning towards Promises

### ISSUE THREAD

**Issue by jeswin** [tj/co#187]
I understand co is now recommending Promises. The README says "This (generator functions) should generally be avoided as we should be moving towards spec-compliant Promises instead". 
But on the other hand, Promises give no useful stack traces for errors. The "work-around" I was using was to use delegating yield (yield*) everywhere and wrapping node-style functions in generator functions. 

Edit: Sorry I misunderstood, you can close this. I misread the README to prefer returning Promises. It seems that is not what you're saying; you're just saying always yield promises.

**Comment by tj** [comment]
yup! weeding out the ad-hoc stuff that I originally added since it wont be compatible with async/await

**Comment by ide** [comment]
If I'm understanding the advice in the README correctly, it is recommending to wrap every generator function with `co.wrap` to return a promise. Shouldn't generators be recommended because the code style matches async/await's a lot more?

The example I have in mind is something like:
```js
function* readConfig() {
  return yield readJSONFile('config.json');
}

function* readJSONFile(path) {
  var contents = yield promisifiedFS.readFile(path, 'utf8');
  return JSON.stringify(contents);
}
```

The key part being that `readFileJSON('config.json')` is a generator, not a promise. I believe this is desirable since you don't have the verbosity of creating intermediate promises. The translation to async/await is very straightforward as well and almost mechanical.

**Comment by EvanCarroll** [comment]
I for one would have liked to see @ide's questioned answered, because I agree with him and came to the same question myself. Just replace yield with `await`.

**Comment by tj** [comment]
Either works, depending on the case, if it's simple just a promise is fine.
