### ISSUE TITLE
Naming conventions?

### ISSUE THREAD

**Issue by ronag** [tj/co#190]
What's the best practice in terms of naming convention, i.e. "async/generator" vs "regular" functions?

In the .NET world usually all "async" functions are postfixed with "Async" e.g. "FooAsync". However, I have not seen any such practice in the node.js world? What thoughts are there on this?

Right now, it is a bit difficult to know if one should "await/yield" on a function or not without looking at its actual signature, i.e. it is difficult to spot missing "await/yields" when reviewing code.

Maybe all public module level functions should be "async", even if their implementation is synchronous and let the runtime optimize away the overhead?

**Comment by madbence** [comment]
Well, the module name (`co-foo`) tells that you should `yield` returned values.

**Comment by ronag** [comment]
Well, that only partly solves the problem. Then you have to keep jumping between the current line and the top to see whether the function comes from a "co-" library. And what about your own function in you current project? Also, what if you have a module that most but not all functions are async?

**Comment by yanickrochon** [comment]
If I may pitch in; First, this is not Co's responsibility to dictate any convention regarding your project. You can adopt any convention you like, however Node.js adopts an async-first naming convention and postfix an `Sync` on functions otherwise (i.e. `read` vs `readSync`).

As for Co modules, they should not mix synchronous and asynchronous functions liberally in their API; they are `co-*` modules, therefore are expected to declare an asynchronous API for consistency. .Net does not work in this manner and they require adding suffixes for readability, since asynchronism was introduced as a feature and Node.js is all about being async in the first place.

**Comment by tj** [comment]
the `co-*` thing is/was mostly just because virtually every reasonable name is exhausted in npm

**Comment by yanickrochon** [comment]
Sure, but I always thought it to be, actually, a convenient and clever categorisation convention.

**Comment by jonathanong** [comment]
everything should be promises eventually anyways, so `co-*` stuff should be going away :)

**Comment by ronag** [comment]
"First, this is not Co's responsibility to dictate any convention regarding your project."

Yes, that is quite obvious.

"Node.js adopts an async-first naming convention and postfix an Sync on functions otherwise (i.e. read vs readSync)"

Not really... e.g. you don't have ```path.basenameSync```...

**Comment by yanickrochon** [comment]
No, you're mixing things here, `path` is a module (and do not declare async functions at all, thus there's no need to add the `Sync` suffix), and `fs` is another, having async and sync'ed functions. Since the asynchronous API is preferred, a synchronous none is provided with the suffix to differentiate. This is the standard in Node.js.

**Comment by ronag** [comment]
What am I mixing? See my previous point where whether the module is async or not is not very helpful since you'd have to figure out from which module every function comes, which is especially difficult of member functions.

And again, the way I understand it, the way the ```Sync```postfix is used in node is never for regular non-blocking synchronous calls. Basically all ```Sync``` calls in NodeJS are a nono, i.e. not a good idea to use.

Yes, I understand that the standard in node is that you don't actually care to give any hints on whether a function is async or not, which is why I started this discussion.

**Comment by madbence** [comment]
What about allowing to `yield` *everything*? The returned values are then turned into promises via `Promise.resolve`.

Well, it's not really consistent, but it's very convenient:

```js
co(function* () {
  var foo = yield bar();
})

function bar() {
  return 1337;
}

// I've changed my mind, bar should be async!
// And I don't have to change the way i call this function
function bar() {
  return new Promise(function (reject, resolve) {
    setTimeout(function () {
      resolve(1337);
    }, 1000);
  });
}
```

I'm not sure what the spec/proposal says about `await`-ing on non-promises, but I guess we should follow it.

**Comment by dtinth** [comment]
I agree about being able to yield just anything. Just make sure that the result is always asyncronously yielded. This also makes it possible to write something like this:

```js
co(function*() {
  for (;;) {
    process()
    display()
    yield
  }
})
```

According to [ecmascript-asyncawait](https://github.com/lukehoban/ecmascript-asyncawait#awaiting-non-promise), awaiting a non-Promise is possible.

> ### Awaiting Non-Promise
>
> When the value passed to `await` is a Promise, the completion of the async function is scheduled on completion of the Promise.  For non-promises, behaviour aligns with Promise conversation rules according to the proposed semantic polyfill.

**Comment by jonathanong** [comment]
@dtinth that document hasn't been updated in a while, and most likely async/await is only going to support promises because supporting anything else will become confusing and complicated for everybody involved.

guys - just use promises. stop with `co-` - modules should work with an without `co`. there's no need to fragment the ecosystem!
