### ISSUE TITLE
some objects are not yieldable

### ISSUE THREAD

**Issue by ylxdzsw** [tj/co#253]
I found that objects whose constructors are not `Object` fail to match `isObject` in co, like `Object.create(null)`, but it was not mentioned in [document](https://github.com/tj/co#objects) at all.

**Comment by luckydrq** [comment]
Should  `isObject` change to adapt `Object.create(null)` case?

**Comment by tj** [comment]
Why would you yield `Object.create(null)`? passing a literal is the only case we should support really, even that is sort of "deprecated", since it's not async/await friendly.

**Comment by dvlsg** [comment]
This just caught me. I was using an object like a map / lookup, and just wanted to nuke all of the additional `prototype` items, since the keys could technically be anything (including `toString`, etc). Not a huge deal, I can just use `hasOwnProperty` instead. Or an actual map. Or convert to an array and `yield Promise.all(values)`, since that's better as far as async/await is concerned. 

Might be nice if an error was thrown, though? The behavior I saw was that my `yield` to `co` hung for "forever". Confused me for a bit, thought one of my api calls was taking forever / timing out.
