### ISSUE TITLE
What was the reason to make co silently ignore exceptions if no catch block provided?

### ISSUE THREAD

**Issue by aa6** [tj/co#294]
I mean
```coffeescript
co ->
  throw Error("Error 2016")
```
will not print any output because I forgot to add `.catch (err) ->` block here. And I always stumble upon this behavior and then spend a decent amount of time to understand why something doesn't work when there is no errors in the output. 
Is there some strong reason to choose this behavior over just throwing an error if no catch block was specified? If there is, could you add some note about it in the `Readme.md`?

**Comment by 131** [comment]
Promises are asynchronous so there is no context to "throw" errors (or try/catch them), but the global context. co, and no libraries will never manage/trigger global errors for you.

**Comment by aa6** [comment]
@131 But why? Is it just a common practice? Or there is some serious reasons to hide errors instead of triggering them in global scope?

**Comment by targos** [comment]
There is an easy way to transform your unhandled rejections into global errors. You just need to add an [event handler](https://nodejs.org/dist/latest-v6.x/docs/api/process.html#process_event_unhandledrejection) in your application. Example:

```js
process.on('unhandledRejection', (reason, p) => {
  throw reason;
});
```

**Comment by aa6** [comment]
@targos Wow, didn't knew the `unhandledRejection` event exists. Thank you for pointing this out.

**Comment by freiit** [comment]
While this fixes (debugging) issues in most cases, some unexpected behavior can occur (not only with co):

One would assume after 2000ms you would get 'e bad', but actually end up with 'p bad' after 1000ms.

So if you introduce an event handler, make sure from now on ALL your promises have a catch method assigned before they are rejected, otherwise the event handler picks them first.

let p = new Promise((_, rej) => setTimeout(() => rej('bad'), 1000))

setTimeout(() => {
  p.catch(e => console.log('e', e))
}, 2000)

process.on('unhandledRejection', (reason, p) => {
  console.log('p', reason)
  process.exit()
});

**Comment by ivan-kleshnin** [comment]
> There is an easy way to transform your unhandled rejections into global errors

An easy way! You just need to do that in every separate script (or import appropriate file)... 😈
