### ISSUE TITLE
Process yield undefined

### ISSUE THREAD

**Issue by JWo1F** [tj/co#306]
Hi there! What do you think about `yield undefined`? I think this should be handled co as `Promise.resolve(undefined)`

**Comment by ifsnow** [comment]
Could you tell me why you need `yield undefined` instead of `Promise.resolve(undefined)`?
Frequently used? It would be nice if there're an example.

I'm curios about this case.

**Comment by keenahn** [comment]
I'm going to vote no on this suggestion. `yield undefined` is usually an error, and I would want this to throw.

**Comment by ORESoftware** [comment]
maybe try this

`yield x() || 'whoops'`

**Comment by JWo1F** [comment]
@ifsnow 

```js
function asyncFn(user) {
  if(!user) return;
  const userName = user.name + ' ' + user.lastname;
  if(userName != 'Alex Wolf') return;
  user.fullname = userName;

  return use(user); // returning promise
}

function* main() {
  const user = yield asyncFn(); // error!
}
```

**Comment by ifsnow** [comment]
@JWo1F I think you can solve it by fixing your code without co's help.

Here is the code I tested.

```js
function use(user) {
    return new Promise(function (resolve, reject) {
        return resolve(user);
    });
};

function asyncFn(user) {
    if(!user || user.name !== 'Alex' || user.lastname !== 'Wolf') {
        return Promise.resolve(undefined);
    }

    user.fullname = user.name + ' ' + user.lastname;

    return use(user);
};

co(function *() {
    const user = {
        name : 'Alex',
        lastname : 'Wolf'
    };

    const processedUser = yield asyncFn(user);
});
```

I hope this helps.

**Comment by clearly** [comment]
@ifsnow Last I checked that's **more code**. I just hit the need for this tonight. I have an entire module abstraction that was not originally built for `yield`ing. I'd like to start introducing the concept of generators into some of those modules.

Without being able to `yield undefined` I need to restructure/refactor the entire module abstraction across all modules because some modules manipulate data structures but don't actually return anything. Whereas if `yield undefined` was supported I could very easily introduce generators without restructuring the entire code base.

**Comment by ifsnow** [comment]
@clearly It seems like `co` doesn't be maintained well. so, I added the way to skip errors for unsupported objects to `co-booster` that I made. `co-booster` is a performance tuning version of `co`. If you're already using `co`, you can make it work more faster by changing only the module. It's fully compatible with `co`.

[Here is co-booster](https://github.com/ifsnow/co-booster)

If you set skipUnsupportError, `co` will no longer throw errors for unsupported objects.

```js
co.skipUnsupportError = true;

co(function* () {
  yield undefined;
});
```

I hope this helps.
